### ISSUE TITLE
Birth date mistakenly interpreted as previous day

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#513] opened 2022-08-08 01:21 UTC
It appears when the database is uploaded from an XLS file, the data for the birthyear is wrong. All athletes are showing as BIRTHYEAR-1

Attaching registration sheet and owlcms database
[owlcms - 4.33.3 - birthyear bug.zip](https://github.com/jflamy/owlcms4/files/9277981/owlcms.-.4.33.3.-.birthyear.bug.zip)

**Comment by jflamy** [comment] 2022-08-08 01:47
I loaded the registration file and the 3 athletes whose name starts with BE are all correctly loaded with their birth year as in the Excel file.  First Athlete 384 is correctly shown as 2008.

**Comment by jarble7** [comment] 2022-08-08 01:50
Im not sure why my system would be different. I uninstalled my software and used the same registration file as I uploaded

The database shows different dates
![image](https://user-images.githubusercontent.com/45324279/183322858-b0e567da-e287-4586-9e8c-1336e5cba047.png)

**Comment by jarble7** [comment] 2022-08-08 01:53
[2022 Ogopogo Start List.pdf](https://github.com/jflamy/owlcms4/files/9278058/2022.Ogopogo.Start.List.pdf)
This start list was generated by the same information.

**Comment by jarble7** [comment] 2022-08-08 01:55
[exportRegistration_2022-08-07_21h54;26.zip](https://github.com/jflamy/owlcms4/files/9278063/exportRegistration_2022-08-07_21h54.26.zip)
Data exported directly from the same database you are using in the excel file above

**Comment by jarble7** [comment] 2022-08-08 01:56
I am using Windows 11. Is that different from your test setup?

**Comment by jflamy** [comment] 2022-08-08 13:26
I am able to reproduce the problem.  The default in the database is to expect a full birth date.  The workaround is to unset the "birth date only" option on the competition info page, hit update button at the top right,  load the file -- all athletes will be  born on January 1, and then reset the checkbox +update button again.

**Comment by jflamy** [comment] 2022-08-08 16:35
Currently unable to reproduce the problem (added traces and what I thought was a recipe to reproduce no longer does).  The plot thickens.

**Comment by jflamy** [comment] 2022-08-08 19:02
Well, it is indeed a time zone problem.  The database drivers are apparently trying to be smart and assume that I wrote UTC in the database and I want to read it back to a local time.  Which is not at all what I want.

**Comment by jflamy-dev** [comment] 2022-08-09 00:45
Tentative fix will be in 4.33.4-rc04 in the prerelease

**Closed** 2022-08-15 14:09 UTC
