### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by fastlines** [jflamy/owlcms4#1020] opened 2024-06-26 14:11 UTC
I live in India so I don't know that much English.

You can make an attempt board of this type. I am attaching the video link. See its attempt board and make it of that type.

https://youtube.com/shorts/j1V36WC5zPQ 

Video Link Attach........

**Comment by scottgonzalez** [comment] 2024-06-26 14:34
Duplicate of gh-1016

**Closed by scottgonzalez** 2024-06-26 14:34 UTC

**Comment by jflamy** [comment] 2024-06-27 01:25
junk
