### ISSUE TITLE
Problems with "Current Athlete" Display and Functionality

### ISSUE THREAD

**Issue by JohnnieKay** [jflamy/owlcms4#1002] opened 2024-06-21 11:28 UTC
I have encountered several issues with the latest versions of the program:

1. It is not possible to change the background of the "Current Athlete" display tab.
2. The "Current Athlete" function tends to freeze after some time.
3. The athlete attempt results displayed at the bottom are often incorrect.
4. Occasionally, other readings are also displayed inaccurately.

**Steps to Reproduce:**

1. Navigate to the "Current Athlete" display tab.
2. Attempt to change the background.
3. Observe the freezing of the "Current Athlete" function after some time.
4. Check the athlete attempt results displayed at the bottom.
5. Observe any other readings for inaccuracies.

**Expected Behavior:**

- Ability to change the background of the "Current Athlete" display tab.
- The "Current Athlete" function should operate without freezing.
- Accurate display of athlete attempt results.
- Accurate display of other readings.

**Actual Behavior:**

- Unable to change the background of the "Current Athlete" display tab.
- The "Current Athlete" function freezes after some time.
- Athlete attempt results are often incorrect.
- Occasionally, other readings are displayed inaccurately.

**Environment:**

- Program Version: 49.0.0
- Operating System: Windows 11
- Browser: Chrome

Could you please advise if there is a known solution to these problems, or if the issue might be within the CMS system itself?

Thank you.

**Comment by jflamy** [comment] 2024-06-21 13:36
Please tell us exactly what version of owlcms you are using and how you are using it.  If you are using a Chrome display, it CANNOT be a background tab because the browser will put background tabs to sleep and they will miss events. Make sure it is the selected tab and make sure the window is not obstructed by any other.
I am currently running a simulation of a large competition and there is no difference between the attempt board and the current athlete -- they are perfectly synchronized.
![image](https://github.com/jflamy/owlcms4/assets/678663/919d0236-38fd-42f9-afaa-1be2adee21ca)

**Comment by jflamy** [comment] 2024-06-21 13:37
Closing until a reproducible scenario is found.

**Comment by jflamy** [comment] 2024-06-21 13:39
Providing a screen video with the attempt board and current athlete side by side, and details on your setup would be necessary.

**Comment by scottgonzalez** [comment] 2024-06-21 14:19
Confirmed with live data.

**Comment by scottgonzalez** [comment] 2024-06-21 14:22
![IMG_3927](https://github.com/jflamy/owlcms4/assets/141167/300f8c41-a10f-4a8b-b355-115d59736588)
![IMG_3928](https://github.com/jflamy/owlcms4/assets/141167/b7c3efc1-efd5-43cd-9b1e-6a4c4a107f0b)
![IMG_3929](https://github.com/jflamy/owlcms4/assets/141167/5dfede4d-e0a1-4c56-8202-9e7bb3932065)

**Comment by jflamy** [comment] 2024-06-21 15:10
There is another issue open about improving the synchronization of the top
decision lights with the bottom display update.
That could be related.

**Closed** 2024-06-21 16:01 UTC
Labels: cannot reproduce

**Comment by jflamy** [comment] 2024-06-21 16:34
Fixed in 49.0.1-rc01.    The bottom scoreboard line will also update in sync with the decision lights, which is more intuitive.
That bug had been there since... forever...
