### ISSUE TITLE
DISPLAY OF RECORDS

### ISSUE THREAD

**Issue by AJAYDAS75** [jflamy/owlcms4#276] opened 2020-01-13 09:07 UTC
Respected Sir it is humble request that if the records display can be added into the running score board and same can be automatically updated as soon as the new record is created.Thank you.

**Comment by jflamy** [comment] 2020-01-13 12:43
I see no way of fitting that together with the leaderboard on the types of
displays used by clubs and state federations.
Maybe as a separate display.
The other issue is that if a record is broken you need to be able to update
it, which means writing an editing interface, and the ability to
import/export records.
So I will log this idea as a long term project.
-- 
(Envoyé de mon téléphone mobile.)

**Comment by AJAYDAS75** [comment] 2020-01-13 13:00
Thank you sir for considering the suggestion. 

Sent from Yahoo Mail on Android 
 
  On Mon, 13 Jan 2020 at 18:13, Jean-François Lamy<notifications@github.com> wrote:   I see no way of fitting that together with the leaderboard on the types of
displays used by clubs and state federations.
Maybe as a separate display.
The other issue is that if a record is broken you need to be able to update
it, which means writing an editing interface, and the ability to
import/export records.
So I will log this idea as a long term project.
-- 
(Envoyé de mon téléphone mobile.)

**Comment by jflamy** [comment] 2022-02-22 17:45
Duplicate of #400

**Closed by jflamy** 2022-02-22 17:45 UTC
Labels: duplicate
